<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Transpose.aspx.cs" Inherits="WebSandbox.Transpose" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <script type="text/javascript" src="Scripts/jquery-1.8.2.min.js"></script>
    <script type="text/javascript" src="Scripts/transpose.js"></script>
    <script type="text/javascript">

        function keyChanged() {
            var chord = $('#src')[0].value;
            var key = $('#keyStart')[0].options[$('#keyStart')[0].selectedIndex].value;
            var distance = parseInt($('#keyTranspose')[0].options[$('#keyTranspose')[0].selectedIndex].value);
            $('#dst')[0].innerText = TransposeChord(chord, key, distance);
        }

    </script>
    <style type="text/css">
        /* Generated by Font Squirrel (http://www.fontsquirrel.com) on August 17, 2012 */
        @font-face {
            font-family: 'jamcharts';
            src: url('jamcharts-webfont.eot');
            src: url('jamcharts-webfont.eot?#iefix') format('embedded-opentype'),
                 url('jamcharts-webfont.woff') format('woff'),
                 url('jamcharts-webfont.ttf') format('truetype'),
                 url('jamcharts-webfont.svg#jamchartsregular') format('svg');
            font-weight: normal;
            font-style: normal;
        }

        /* Generated by Font Squirrel (http://www.fontsquirrel.com) on August 12, 2012 */
        @font-face {
            font-family: 'jazztext';
            src: url('jazztext-webfont.eot');
            src: url('jazztext-webfont.eot?#iefix') format('embedded-opentype'),
                 url('jazztext-webfont.woff') format('woff'),
                 url('jazztext-webfont.ttf') format('truetype'),
                 url('jazztext-webfont.svg#jazztextregular') format('svg');
            font-weight: normal;
            font-style: normal;
        }
        
        .key {
        	font-family: jazztext;
        	font-size: 24pt;
        }  	
    </style>
</head>
<body>
    <form id="form1" runat="server">
    <div>
        <select class="inputControl" id="keyStart" onchange="UpdateKeyList(this.options[this.selectedIndex].value, true);keyChanged();">
            <option value="C" selected="selected">C</option>
            <option value="Db">Db</option>
            <option value="D">D</option>
            <option value="Eb">Eb</option>
            <option value="E">E</option>
            <option value="F">F</option>
            <option value="Gb">Gb</option>
            <option value="G">G</option>
            <option value="Ab">Ab</option>
            <option value="A">A</option>
            <option value="Bb">Bb</option>
            <option value="B">B</option>
        </select>
        <input type="text" id="src" oninput="keyChanged();" />
        <input type="text" id="dst"/>
    </div>
    <br/><br/>
    <div>
        <select id="keyTranspose"  style="font-family: jazztext; font-size: 24pt;margin-left:12px; margin-right:12px;" onchange="keyChanged();">
            <option value="-5">&nbsp;-5&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;G&nbsp;</option>
            <option value="-4">&nbsp;-4&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A&#x00D1&nbsp;</option>
            <option value="-3">&nbsp;-3&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A&nbsp;</option>
            <option value="-2">&nbsp;-2&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;B&#x00D1&nbsp;</option>
            <option value="-1">&nbsp;-1&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;B&nbsp;</option>
            <option value="0" selected="selected">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;C&nbsp;</option>
            <option value="1">&nbsp;+1&nbsp;&nbsp;&nbsp;&nbsp;D&#x00D1&nbsp;</option>
            <option value="2">&nbsp;+2&nbsp;&nbsp;&nbsp;&nbsp;D&nbsp;</option>
            <option value="3">&nbsp;+3&nbsp;&nbsp;&nbsp;&nbsp;E&#x00D1&nbsp;</option>
            <option value="4">&nbsp;+4&nbsp;&nbsp;&nbsp;&nbsp;E&nbsp;</option>
            <option value="5">&nbsp;+5&nbsp;&nbsp;&nbsp;&nbsp;F&nbsp;</option>
            <option value="6">&nbsp;+6&nbsp;&nbsp;&nbsp;&nbsp;G&#x00D1&nbsp;</option>
        </select>
        </div>
    </form>
</body>
</html>
